specVersion: "1.0.0"

name: "subql-example-arbitrum-winr-rewards"
version: "0.0.1"
runner:
  node:
    name: "@subql/node-ethereum"
    version: "*"
  query:
    name: "@subql/query"
    version: "*"
description: "This SubQuery Arbitrum Example project indexes all Arbitrum WINR Staking Rewards."
repository: "https://github.com/subquery/subql-example-arbitrum-winr-rewards"

schema:
  file: "./schema.graphql"

network:
  # chainId is the EVM Chain ID, for Arbitrum this is 42161
  # https://chainlist.org/chain/42161
  chainId: "42161"
  # This endpoint must be a public non-pruned archive node
  # We recommend providing more than one endpoint for improved reliability, performance, and uptime
  # Public nodes may be rate limited, which can affect indexing speed
  # When developing your project we suggest getting a private API key
  # You can get them from OnFinality for free https://app.onfinality.io
  # https://documentation.onfinality.io/support/the-enhanced-api-service
  endpoint: ["https://arbitrum.api.onfinality.io/public"]
  # Recommended to provide the HTTP endpoint of a full chain dictionary to speed up processing
  dictionary: "https://gx.api.subquery.network/sq/subquery/arbitrum-dictionary-eth"

dataSources:
  - kind: ethereum/Runtime # We use ethereum runtime since Arbitrum is a layer-2 that is compatible
    startBlock: 94503514
    # startBlock: 91117840 # This is the block that the contract was deployed on https://arbiscan.io/tx/0x300b6199816f44029408efc850fb9d6f8751bbedec3e273909eac6f3a61ee3b3
    options:
      # Must be a key of assets
      abi: winr-staking
      address: "0xddAEcf4B02A3e45b96FC2d7339c997E072b0d034" # This is the contract address for WINR Staking https://arbiscan.io/address/0xddaecf4b02a3e45b96fc2d7339c997e072b0d034
    assets:
      winr-staking:
        file: "./abis/winr-staking.abi.json"
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleDividendBatch
          kind: ethereum/LogHandler # We use ethereum handlers since Arbitrum is a layer-2 that is compatible
          filter:
            topics:
              ## Follows standard log filters https://docs.ethers.io/v5/concepts/events/
              - ClaimDividendBatch(address indexed user, uint256 reward)
              # address: "0x60781C2586D68229fde47564546784ab3fACA982"
